spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  cloud:
    gateway:
      routes:
        - id: vets-service
          uri: lb://vets-service
          predicates:
            - Path=/api/vet/**
          filters:
            - StripPrefix=2
        - id: visits-service
          uri: lb://visits-service
          predicates:
            - Path=/api/visit/**
          filters:
            - StripPrefix=2
        - id: customers-service
          uri: lb://customers-service
          predicates:
            - Path=/api/customer/**
          filters:
            - StripPrefix=2

management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    env:
      show-values: always
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  wavefront:
    application:
      name: api-gateway
    uri: http://telegraf-collector.tanzu-telegraf-collector.svc.cluster.local:2878
    api-token: my-api-token
  tracing:
    sampling:
      probability: 1.0

---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888
