apiVersion: apps.tanzu.vmware.com/v1
kind: ContainerApp
metadata:
  name: spring-petclinic-visits-service
spec:
  build:
    buildpacks: {}
    nonSecretEnv:
      - name: BP_JVM_VERSION
        value: "17"
    path: ../..
  ports:
    - name: main
      port: 8082
  replicas: 1
  resources:
    cpu: 300m
    memory: 1Gi
